### ISSUE TITLE
Add Github Action for check licenses

### ISSUE THREAD

**Issue by liangyuanpeng** [apache/incubator-eventmesh#310]
We can add Github Action for automatically check licenses and review future pull requests.  

This topic was first mentioned in https://github.com/apache/incubator-eventmesh/pull/303#issuecomment-824457253  and i had realy work for it.  

Some result you can see https://github.com/liangyuanpeng/incubator-eventmesh/pull/1   .

How can we use github-actions bot robot instead of myself?  Thanks   @kezhenxu94  

![image](https://user-images.githubusercontent.com/28711504/115826160-0a6fee00-a43d-11eb-91a5-891ced2951db.png)
  

![image](https://user-images.githubusercontent.com/28711504/115826185-12c82900-a43d-11eb-83fd-ef9241bf92d9.png)

**Comment by kezhenxu94** [comment]
Hi @liangyuanpeng , thanks for your work, I saw that you set a personal token

https://github.com/liangyuanpeng/incubator-eventmesh/blob/ca40d049c6aa5584f07f4aa21febb42d586e3b2a/.github/workflows/maven.yml#L28

which is not necessary and is not allow as per ASF policy, all you need is to do is using the built-in token `${{ secrets.GITHUB_TOKEN }}` like this

https://github.com/apache/skywalking/blob/10e89aa566698e8f4d02e7e2e3ad28bb5a9c4e14/.github/workflows/ci-it.yaml#L42

**Comment by qqeasonchen** [comment]
@liangyuanpeng It is better not to rely on Skywalking, @SteveYurongSu do you have any good suggestions?

**Comment by kezhenxu94** [comment]
> @liangyuanpeng It is better not to rely on Skywalking, @SteveYurongSu do you have any good suggestions?

I’m not sure what you mean by saying “not to rely on skywalking”, this is just a license tool that has nothing to do with runtime dependencies, also, it’s under skywalking as a sub prpject only because it was started by skywalking PMC member.

**Comment by kezhenxu94** [comment]
@qqeasonchen what’s your concern here?

**Comment by SteveYurongSu** [comment]
I think apache/skywalking-eyes is an excellent tool, and we can use it with confidence. It is not only fully functional, but also well integrated with Github Actions, which makes it easy for us to config this excellent tool for our project.

In fact, if I were to make a choice, I would also choose to use apache/skywalking-eyes as our license check tool, but @liangyuanpeng was one step ahead haha. In fact, many famous Apache projects (such as Apache Shardingsphere, see https://github.com/apache/dolphinscheduler/blob/dev/.github/workflows/ci_ut.yml) already use apache/skywalking-eyes as their license check tool: D
 
Yes, I think @qqeasonchen may be worried that apache/skywalking-eyes will bring some runtime dependencies, but as @kezhenxu94 said, we can actually run the license check without any additional dependencies, because apache/skywalking-eyes uses Github Actions.

**Comment by qqeasonchen** [comment]
@kezhenxu94 I am not trust Skywalking, in fact Skywalking is a very good APM project, but I just don’t want to bring some instability due to some changes in dependencies, I hope you can understand, thank you very much for your suggestion and thanks for your contribution @liangyuanpeng.

**Comment by kezhenxu94** [comment]
> @kezhenxu94 I am not distrusting Skywalking, in fact Skywalking is a very good APM project, but I just don’t want to bring some instability due to some changes in dependencies, I hope you can understand, thank you very much for your suggestion and thanks for your contribution @liangyuanpeng.

Definitely, I understand. It's reasonable for you to take care of the stability of this project, if I were you I would did the same thing :) , and that's why I asked what are your concerns and I was trying to address them, so it turns out to be a misunderstanding, right? You were concerning it will bring runtime dependencies?

**Comment by xwm1992** [comment]
Yeah, If you can just submit a Github Action for Check Lisence, I think it would be more appropriate and more acceptable by community, thanks.
