### ISSUE TITLE
Split handler form ClientManageController

### ISSUE THREAD

**Issue by ruanwenjun** [apache/incubator-eventmesh#359]
Split handler from controller, make the controller code more concise, and it is convenient to write unit test.

**Comment by qqeasonchen** [comment]
Just for UT?

**Comment by ruanwenjun** [comment]
@qqeasonchen I think it can also make the controller cleaner, if we need to add new handler in the future, we don't want to write it in the controller, because if we do this, the controller will become a huge class.

**Comment by lrhkobe** [comment]
@ruanwenjun I think it is unnecessary to split the controller,because the cotroller is just as a tool class ,not associcatesd with business, and it's function may be  certain.Split it may lead to an increase in the number of classes and system complexity. 
About it is more convenient to write unit test? I have not got it,, can you make it clear?

**Comment by ruanwenjun** [comment]
@lrhkobe Maybe you are right, if you are sure that this change is not necessary, you can close this issue, thanks.

**Comment by qqeasonchen** [comment]
@ruanwenjun Your idea is good, discuss is open.

**Comment by lrhkobe** [comment]
@ruanwenjun Can you offer some unit test demo which is mentioned in this issue？

**Comment by ruanwenjun** [comment]
@lrhkobe Ok, I have written a simple unit test.
![image](https://user-images.githubusercontent.com/22415594/119003604-6ee08780-b9c0-11eb-82eb-76166f07093d.png)
This code just tests one simple case, in each handler, there may be multiple cases that need to be tested.
I think if We test all handlers in one controller class, this may make the controller class very complicated.
